[package]
name = "aoc-2025"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "0.14.0"
regex = "1.12.2"
rayon = "1.11.0"
petgraph = "0.8.3"
num = "0.4.3"
num-bigint = "0.4.6"
z3 = { version = "0.19.5", features = ["gh-release"]}
